version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dev_tracker_db
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: